name: Run Ruff

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
            channels: conda-forge,bioconda,defaults
            auto-activate-base: false
            activate-environment: test_env
            environment-file: .github/envs/test_env.yml

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Ruff
        run: ruff check . --statistics

      - name: Tear down Docker Compose
        if: always()
        run: make down